### ISSUE TITLE
Kirke build tool

### ISSUE THREAD

**Issue by shawnbot** [shawnbot/TODO#20]
> KIRKE (Circe) was a goddess of sorcery (_pharmakeia_) who was skilled in the magic of transmutation, illusion, and necromancy. She lived on the mythical island of Aiaia (Aeaea) with her nymph companions.

[Kirke](http://www.theoi.com/Titan/Kirke.html) is what I'm calling my ideal and (so far) mythical build tool that can simply transform different types of source files (ES6, Sass, design assets) into their corresponding, production-ready assets (browser-ready JS and CSS with source maps, compressed images, custom fonts, etc. etc.).
- Configurable via YAML, JSON, `package.json`, or JS... maybe with [cosmiconfig](https://github.com/davidtheclark/cosmiconfig)?
- Allows you to extend named configs, a la eslint; or has the concept of "recipes" a la [Felt](https://github.com/cognitom/felt)
- Uses [Metalsmith](http://www.metalsmith.io/) under the hood to transform source files 

Some usage examples:

``` sh
# build src => dist using the default configuration (or as defined in package.json)
kirke --from src --to dist

# watch using YAML config, which specifies source and dest dirs
kirke --config .kirke.yml --watch

# use a recipe, i.e. kirke-recipe-18F
kirke --recipe 18F

# or, extend via configuration
echo 'extends: 18F' > .kirkerc.yml
kirke
```

Maybe a sample configuration looks like:

``` yaml
'**/*.js':
  - browserify:
      transform:
        - rollupify: {}
        - babelify: {presets: [es2015-rollup]}
        - uglifyify: {global: true}

'**/*.s[ac]ss':
  - sass:
      includePath: [node_modules/uswds/src/stylesheets]
      sourceMap: true
  - postcss: [cssnext, cssnano]

'**/*.{png,jpg}':
  - imageoptim: {}

'**/*.svg':
  - svgo: {}
```
